use_frameworks!

target 'StanwoodDebugger_Example' do
  pod 'StanwoodDebugger', :path => '../'
  pod 'StanwoodCore', '~> 1.2.1'
  
  target 'StanwoodDebugger_Tests' do
    inherit! :search_paths

    
  end
end
