use_frameworks!

target 'StanwoodDebugger_Example' do
  pod 'StanwoodDebugger', :path => '../'
  pod 'StanwoodCore', '~> 1.4.1'
  
  target 'StanwoodDebugger_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if ['Pulsator'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
