use_frameworks!

target 'StanwoodDebugger_Example' do
  pod 'StanwoodDebugger', :path => '../', :configurations => ['Debug']
  
  target 'StanwoodDebugger_Tests' do
    inherit! :search_paths

    
  end
end
